% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Social Network Analysis Report on Wine Review Data},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Social Network Analysis Report on Wine Review Data}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\section{Social Network Analysis Report über
Weinbewertungs-Daten}\label{social-network-analysis-report-uxfcber-weinbewertungs-daten}

\subsection{Einleitung und
Forschungsfrage}\label{einleitung-und-forschungsfrage}

In der folgenden Arbeit wird der Datensatz ``Wine
Reviews''(\url{https://www.kaggle.com/datasets/zynicide/wine-reviews/data})
des Kaggle-Users ``Zackthoutt'' analysisert und behandelt. Der Datensatz
wurde von der Website \url{https://www.wineenthusiast.com/} gescraped
und durch ``Zackthoutt'' auf Kaggle bereitgestellt.

Als Anreicherung wird weiterhin der Datensatz
``wine-producing-countries-2023'' der website:
\url{https://worldpopulationreview.com/country-rankings/wine-producing-countries}
verwendet. Dieser Datensatz enthält die Produktion von Wein aller
Länder.

Wein ist eines der ältesten und am weitesten verbreiteten alkoholischen
Getränke weltweit. Mit einer ca. 8000 Jahren alten Geschichte hat sich
rund um das Thema wein eine vielfälltige und komplex Kutur gebildet.
Wein und seine Vielfalt hat auch mein persönliches Interesse geweckt
weshalb ich diesen Report dem Thema der Bewertung von Wein sowie seiner
Produktion widmen möchte.

Die Fragen die dieser Report beantworten soll sind:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Welches Land stellt die meißten der bewerteten Weine?
\item
  Welches Land bekommt durchschnittlich die besten bewertungen?
\item
  Welches Land hat das beste Preis-Punkte-Verhältis?
\item
  Stimmt die Verteilung der bewerteten Weine mit der weltweiten
  Produktion (je Land) von Wein überein?
\item
  In welcher Relationen stehen die länder in Bezug auf die Anzahl der
  bewerteten Weine zueinander?
\end{enumerate}

\subsection{Analysestrategie}\label{analysestrategie}

Zur beantfortung der Fragen werden zuerst verschiedene Daten benötigt:

\begin{itemize}
\item
  Das Herkunftsland des Weines
\item
  Der Name bzw. ein eindeutig zuzuweisender Parameter
\item
  Die erhaltenen Punkte
\item
  Der Preis
\item
  Die Weinproduktion der jeweiligen Länder insgesammt
\item
  Name des Testers
\end{itemize}

Es gibt weiterhin Faktoren die aus den gegebenen Daten errechnet werden
müsse:

\begin{itemize}
\item
  Die Anzahl der Weine je Land
\item
  Der Durchschnitsspreis von weinen je Land sowie die Punkteanzahl
\item
  Das Verhältnis des Preis- und Punktedurchschnits je Land
\item
  Die Ähnlichkeit bzw. Relation der verschiedenen Länder im Bezug auf
  die Anzahl der Weine
\item
  Die Anzahl der getesteten Weine je nach Tester und Land
\end{itemize}

Der Großteil der Fragen lässt sich vor allem durch eine quantitative
Datenanalyse beantworten, für Frage 4 ist es jedoch effektiver ein
Netzwerk zu erstellen da dort die Relationen der länder Miteinander
besser zur geltung kommen, des weiteren können so Cluster identifiziert
werden welche weitere Rückschlüsse erlauben. Auch Frage 6 ist mit einem
Netzwerk am besten zu veranschaulichen.

\subsection{Analyse des Datensatzes}\label{analyse-des-datensatzes}

\subsubsection{Data Exploration \&
Cleaning}\label{data-exploration-cleaning}

Zuerst muss der Datensatz ``winemag-data-130k-v2.csv'' welcher die Daten
für die Bewertungen der verschiedenen Weine enthält geladen werden.
Ebenfalls wird der zweite Datensatz zur anreicherung geladen und
formatiert.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# setzen der benötigten Packages }
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(igraph)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(gridExtra)}
\CommentTok{\# laden des Datensatzes}
\NormalTok{winemag\_data\_130k\_v2 }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"winemag{-}data{-}130k{-}v2.csv"}\NormalTok{,}\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}
\CommentTok{\# zuweisen des Datensatzes zu einem neue Data Frame zur weiterverarbeitung}
\NormalTok{df }\OtherTok{\textless{}{-}}\NormalTok{ winemag\_data\_130k\_v2}

\CommentTok{\# zweiten Datensatz laden und umwandeln um ihn in der anschließenden Analyse Nutzen zu können}
\NormalTok{wineproduction\_data\_2023 }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"wine{-}producing{-}countries{-}2023.csv"}\NormalTok{)}
\NormalTok{df\_wine\_prod }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(}\FunctionTok{select}\NormalTok{(wineproduction\_data\_2023, country, wineProducingCountries\_wineProduction))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# um einen ersten Überblick zu erhalten werden mit head(df,10) die ersten 10 Zeilen ausgegeben}
\FunctionTok{head}\NormalTok{(df,}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 14
##     ...1 country description designation points price province region_1 region_2
##    <dbl> <chr>   <chr>       <chr>        <dbl> <dbl> <chr>    <chr>    <chr>   
##  1     0 Italy   Aromas inc~ Vulkà Bian~     87    NA Sicily ~ Etna     <NA>    
##  2     1 Portug~ This is ri~ Avidagos        87    15 Douro    <NA>     <NA>    
##  3     2 US      Tart and s~ <NA>            87    14 Oregon   Willame~ Willame~
##  4     3 US      Pineapple ~ Reserve La~     87    13 Michigan Lake Mi~ <NA>    
##  5     4 US      Much like ~ Vintner's ~     87    65 Oregon   Willame~ Willame~
##  6     5 Spain   Blackberry~ Ars In Vit~     87    15 Norther~ Navarra  <NA>    
##  7     6 Italy   Here's a b~ Belsito         87    16 Sicily ~ Vittoria <NA>    
##  8     7 France  This dry a~ <NA>            87    24 Alsace   Alsace   <NA>    
##  9     8 Germany Savory dri~ Shine           87    12 Rheinhe~ <NA>     <NA>    
## 10     9 France  This has g~ Les Natures     87    27 Alsace   Alsace   <NA>    
## # i 5 more variables: taster_name <chr>, taster_twitter_handle <chr>,
## #   title <chr>, variety <chr>, winery <chr>
\end{verbatim}

Nachdem der Datensatz nun schonmal exemplarisch geladen ist, kann man
sehen das dieser 14 verschiedene Spalten hat.

Diese sind:

\begin{itemize}
\item
  country
\item
  description
\item
  designation
\item
  points
\item
  price
\item
  province
\item
  region\_1
\item
  region\_2
\item
  taster\_name
\item
  taster\_twitter\_handle
\item
  tittle
\item
  variety
\item
  winery
\end{itemize}

Für unsere Analyse verwenden wir jedoch nur die folgenden Spalten:

\begin{itemize}
\item
  country
\item
  points
\item
  price
\item
  taster\_name
\end{itemize}

\subsubsection{Frage 1 - Welches Land stellt die meisten der bewerteten
Weine?}\label{frage-1---welches-land-stellt-die-meisten-der-bewerteten-weine}

Um herrauszufinden welches Land die meisten Weine in der Bewertung
stellt müssen wir zuerst die Spalten ``country'' sowie ``title'' aus dem
Haupt Dataframe (df) extrahieren. Nun können die Weine je nach Land
aufsummiert werden und in einem Balkendiagramm veranschaulicht werden.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Neuen Dataframe mit den Spalten "country" und "title" bilden}
\NormalTok{df\_WW }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(}\FunctionTok{select}\NormalTok{(df, country, title))}
\CommentTok{\# Anzahl der Einträge je Land zählen }
\NormalTok{df\_WW\_wines\_by\_country }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{table}\NormalTok{(df\_WW}\SpecialCharTok{$}\NormalTok{country))}
\CommentTok{\# Dataframe absteigend sortieren}
\NormalTok{df\_WW\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_WW\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq),]}

\CommentTok{\# Plot der Top 10 Länder erstellen um die prominenteste Nation zu finden}
\FunctionTok{ggplot}\NormalTok{(df\_WW\_wines\_by\_country[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,], }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Var1, }\AttributeTok{y =}\NormalTok{ Freq)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Herkunftsländer bewerteter Weine"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Land"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Anzahl"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Name des Landes und Anzahl der weine ausgeben}
\FunctionTok{print}\NormalTok{(df\_WW\_wines\_by\_country)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                      Var1  Freq
## 43                     US 54504
## 16                 France 22093
## 23                  Italy 19540
## 38                  Spain  6645
## 32               Portugal  5691
## 9                   Chile  4472
## 1               Argentina  3800
## 4                 Austria  3345
## 3               Australia  2329
## 18                Germany  2165
## 30            New Zealand  1419
## 37           South Africa  1401
## 22                 Israel   505
## 19                 Greece   466
## 8                  Canada   257
## 20                Hungary   146
## 7                Bulgaria   141
## 33                Romania   120
## 42                Uruguay   109
## 40                 Turkey    90
## 36               Slovenia    87
## 17                Georgia    86
## 15                England    74
## 11                Croatia    73
## 27                 Mexico    70
## 28                Moldova    59
## 6                  Brazil    52
## 24                Lebanon    35
## 29                Morocco    28
## 31                   Peru    16
## 41                Ukraine    14
## 13         Czech Republic    12
## 26              Macedonia    12
## 34                 Serbia    12
## 12                 Cyprus    11
## 21                  India     9
## 39            Switzerland     7
## 25             Luxembourg     6
## 2                 Armenia     2
## 5  Bosnia and Herzegovina     2
## 10                  China     1
## 14                  Egypt     1
## 35               Slovakia     1
\end{verbatim}

Nachdem man das Diagram sowei die Ausgabe aus der Kosole betrachtet,
sieht man das die USA mit: 54504 das Land sind welche die meisten Weine
Stellen.

\subsubsection{Frage 2 - Welches Land bekommt durchschnittlich die
besten
bewertungen?}\label{frage-2---welches-land-bekommt-durchschnittlich-die-besten-bewertungen}

Um zu errechnen welches Land durschnittlich die beste Punktzahl erhält
müssen wir zuerts einen Dataframe erzeugen welcher die Spalten:
``country'', ``points'' und ``title'' enthält.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Erzeugen des Dataframes}
\NormalTok{df\_WW\_points }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(}\FunctionTok{select}\NormalTok{(df, country,points,title))}
\NormalTok{df\_WW\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(df\_WW\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Var1),]}
\CommentTok{\# Aggregation der Werte sowie die Berechnung der Durchschnittlichen Punkte Anzahl}
\NormalTok{df\_WW\_points\_avg }\OtherTok{\textless{}{-}} \FunctionTok{aggregate}\NormalTok{(df\_WW\_points}\SpecialCharTok{$}\NormalTok{points, }\FunctionTok{list}\NormalTok{(df\_WW\_points}\SpecialCharTok{$}\NormalTok{country), }\AttributeTok{FUN=}\NormalTok{mean)}
\CommentTok{\# Alphabetisches Sortieren des DF}
\NormalTok{df\_WW\_points\_avg }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_points\_avg[}\FunctionTok{order}\NormalTok{(df\_WW\_points\_avg}\SpecialCharTok{$}\NormalTok{Group}\FloatTok{.1}\NormalTok{),]}
\CommentTok{\# visualisiserung der Verteilung der Punktedurchschnitte}
\FunctionTok{boxplot}\NormalTok{(df\_WW\_points\_avg}\SpecialCharTok{$}\NormalTok{x)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-4-1.pdf}

Durch diesen Boxplot kann man sehen das der Durchschnitt der
durschnittlichen Punktezahl bei ca. 87.65 liegt, es gibt weiterhin
outlier die von \textless84 bis \textgreater90 liegen. Um dies besser zu
veranschaulichen bedarf es jedoch einer anderen Visualisierungsform wie
beispielsweise einem Balkendiagramm.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df\_WW\_points\_avg[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,], }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Group}\FloatTok{.1}\NormalTok{, }\AttributeTok{y =}\NormalTok{ x)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Herkunftsländer bewerteter Weine"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Land"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Durschnittliche Punkte"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Absteigend sortieren und ausgeben des DF}
\FunctionTok{print}\NormalTok{(}\FunctionTok{head}\NormalTok{(df\_WW\_points\_avg[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_WW\_points\_avg}\SpecialCharTok{$}\NormalTok{x),],}\DecValTok{20}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Group.1        x
## 15      England 91.58108
## 21        India 90.22222
## 4       Austria 90.10135
## 18      Germany 89.85173
## 8        Canada 89.36965
## 20      Hungary 89.19178
## 10        China 89.00000
## 16       France 88.84511
## 25   Luxembourg 88.66667
## 3     Australia 88.58051
## 29      Morocco 88.57143
## 39  Switzerland 88.57143
## 43           US 88.56372
## 23        Italy 88.56223
## 22       Israel 88.47129
## 30  New Zealand 88.30303
## 32     Portugal 88.25022
## 40       Turkey 88.08889
## 36     Slovenia 88.06897
## 37 South Africa 88.05639
\end{verbatim}

Nun ist zu erkennen das nachdem man das Balkendiagram sowie die Ausgabe
in der Konsole betrachtet das England das Land mit der höchsten
durschnittlichen punktzahl ist. Hierbei ist es nun jedoch wichtig zu
betrachten das dieser Wert wohlmöglich aufgrund der relativ niedriegen
Anzahl der aus England stammenden bewerteten Weine verzehrt ist. Um nun
zu betrachten wie sehr sich die Punktzahlen um den Durschnitt streuen
betrachten wir außerdem den Standartfehler (SEM) dieser zeigt uns welche
abweichung vom Durschnitt zu erwarten sind.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Standardtabweichnung berechnene}
\NormalTok{df\_WW\_points\_SEM }\OtherTok{\textless{}{-}} \FunctionTok{aggregate}\NormalTok{(df\_WW\_points}\SpecialCharTok{$}\NormalTok{points, }\FunctionTok{list}\NormalTok{(df\_WW\_points}\SpecialCharTok{$}\NormalTok{country), }\AttributeTok{FUN=}\NormalTok{sd)}
\CommentTok{\# SEM berechnen}
\NormalTok{df\_WW\_points\_SEM}\SpecialCharTok{$}\NormalTok{x }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_points\_SEM}\SpecialCharTok{$}\NormalTok{x }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(df\_WW\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq)}
\CommentTok{\#DF absteigend sortieren}
\NormalTok{df\_WW\_points\_SEM }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_points\_SEM[}\FunctionTok{order}\NormalTok{(df\_WW\_points\_SEM}\SpecialCharTok{$}\NormalTok{x),]}
\CommentTok{\# Balkendiagramm der top 10 erstellen }
\FunctionTok{ggplot}\NormalTok{(df\_WW\_points\_SEM[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,], }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Group}\FloatTok{.1}\NormalTok{, }\AttributeTok{y =}\NormalTok{ x)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Durchschnittliche"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Land"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Durchschnittliche Abweichung"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{head}\NormalTok{(df\_WW\_points\_SEM))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Group.1          x
## 43       US 0.01334202
## 23    Italy 0.01895586
## 16   France 0.02048225
## 38    Spain 0.03761533
## 32 Portugal 0.03971597
## 9     Chile 0.04026974
\end{verbatim}

Ziehen wir nun mit in betracht das auch eine geringe Abweichung der
gegebenen Werte vom Durchschnitt eine wichte Rolle spielt so können wir
feststellen das die USA das Land sind bei welchem die geringste
Abweichung von der Durschnittlichen Punkte zu erwarten ist.

Um die Frage zu beantworten ``Welches Land bekommt durschnittlich die
besten Bewertungen?'' kann man also sagen das zwar England das Land mit
dem höchsten durschnittlichen Score ist (91,581) jedoch die USA das Land
sind bei welchem es die niedrigste zu erwartende Streuung vom Durschnitt
gibt (0.0133).

\subsubsection{Frage 3 - Welches Land hat das beste
Punkte-Preis-Verhältnis?}\label{frage-3---welches-land-hat-das-beste-punkte-preis-verhuxe4ltnis}

Um nun festzustellen welche Land das beste Preis zu Punkte Verhältnis
hat werden wir den durschnittlichen Preis errechnene und dann durch die
durschnittlichen Punkte teilen.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# erstellen des bebötigten DF zur berechnung des Durschnittspreis}
\NormalTok{df\_WW\_price }\OtherTok{\textless{}{-}} \FunctionTok{select}\NormalTok{(df, country, price)}
\NormalTok{df\_WW\_price}\SpecialCharTok{$}\NormalTok{price[}\FunctionTok{is.na}\NormalTok{(df\_WW\_price}\SpecialCharTok{$}\NormalTok{price)] }\OtherTok{\textless{}{-}}\FloatTok{0.0}
\CommentTok{\# berechnung des Durschnittspreis}
\NormalTok{df\_WW\_price\_avg }\OtherTok{\textless{}{-}} \FunctionTok{aggregate}\NormalTok{(df\_WW\_price}\SpecialCharTok{$}\NormalTok{price, }\FunctionTok{list}\NormalTok{(df\_WW\_price}\SpecialCharTok{$}\NormalTok{country), }\AttributeTok{FUN=}\NormalTok{mean)}
\NormalTok{df\_WW\_price\_avg }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_price\_avg[}\FunctionTok{order}\NormalTok{(df\_WW\_price\_avg}\SpecialCharTok{$}\NormalTok{Group}\FloatTok{.1}\NormalTok{),]}
\CommentTok{\# erstellen der neuen Spalte für das Preis{-}Punkte{-}Verhältnis}
\NormalTok{df\_WW\_price\_avg}\SpecialCharTok{$}\NormalTok{PPV }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_points\_avg}\SpecialCharTok{$}\NormalTok{x }\SpecialCharTok{/}\NormalTok{ df\_WW\_price\_avg}\SpecialCharTok{$}\NormalTok{x}
\CommentTok{\# sortieren nach PPV}
\NormalTok{df\_WW\_price\_avg }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_price\_avg[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_WW\_price\_avg}\SpecialCharTok{$}\NormalTok{PPV),]}

\CommentTok{\# visualisieren der Ergebnisse sowie ausgabe in die Konsole}
\FunctionTok{boxplot}\NormalTok{(df\_WW\_price\_avg}\SpecialCharTok{$}\NormalTok{PPV)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in bplt(at[i], wid = width[i], stats = z$stats[, i], out =
## z$out[z$group == : Outlier (Inf) in boxplot 1 is not drawn
\end{verbatim}

\includegraphics{Report_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(df\_WW\_price\_avg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                   Group.1         x      PPV
## 14                  Egypt  0.000000      Inf
## 41                Ukraine  9.214286 9.124031
## 5  Bosnia and Herzegovina 12.500000 6.920000
## 21                  India 13.333333 6.766667
## 2                 Armenia 14.500000 6.034483
## 7                Bulgaria 14.645390 6.004358
## 33                Romania 15.241667 5.668671
## 26              Macedonia 15.583333 5.572193
## 35               Slovakia 16.000000 5.437500
## 12                 Cyprus 16.272727 5.357542
## 28                Moldova 16.745763 5.207490
## 10                  China 18.000000 4.944444
## 17                Georgia 18.872093 4.646334
## 31                   Peru 18.062500 4.626298
## 29                Morocco 19.500000 4.542125
## 9                   Chile 20.526163 4.213818
## 19                 Greece 22.124464 3.945102
## 6                  Brazil 21.480769 3.941808
## 32               Portugal 22.458970 3.929397
## 37           South Africa 22.767309 3.867668
## 36               Slovenia 22.816092 3.859950
## 25             Luxembourg 23.333333 3.800000
## 13         Czech Republic 24.250000 3.597938
## 1               Argentina 24.226316 3.579177
## 40                 Turkey 24.633333 3.576004
## 34                 Serbia 24.500000 3.571429
## 11                Croatia 24.753425 3.523520
## 4                 Austria 25.741405 3.500250
## 30            New Zealand 26.153629 3.376320
## 42                Uruguay 26.403670 3.285615
## 27                 Mexico 26.785714 3.182933
## 38                  Spain 27.909556 3.127543
## 22                 Israel 30.762376 2.875958
## 24                Lebanon 30.685714 2.857542
## 16                 France 33.100484 2.684103
## 23                  Italy 34.333316 2.579484
## 3               Australia 34.905109 2.537752
## 8                  Canada 35.295720 2.532025
## 43                     US 36.413089 2.432195
## 20                Hungary 40.369863 2.209365
## 18                Germany 41.379215 2.171422
## 15                England 48.189189 1.900449
## 39            Switzerland 85.285714 1.038526
\end{verbatim}

Wir können nun sehen das die Ukraine das Land ist wessen Weine das beste
Punkte-Preis-Verhältnis aufweisen (9,124), hierbei ist jedoch erneut zu
beachten das die Sample Size eine wichtige rolle Spielt und
möglicherweise das Ergebnis verzehrt. Das schlechteste Verhältnis hat
die Schweiz mit ca. 1,039. Der durschnittliche Score liegt bei ca. 3,8.

\subsubsection{Frage 4 - Stimmt die Verteilung der bewerteten Weine mit
der weltweiten Produktion (je Land) von Wein
überein?}\label{frage-4---stimmt-die-verteilung-der-bewerteten-weine-mit-der-weltweiten-produktion-je-land-von-wein-uxfcberein}

Um herrauszufinden ob die Herkunft der bewerteten Weine mit der
Produktion von wein zusammenhängt verwenden wir hier einen 2. Datensatz
welcher die weltweite Produktion von Wein abbildet.

Zuerst müssen wir nun die Verteilung der weltweiten Weinporduktion
betrachten und danach mit der Anzahl der bewerteten Weine vergleichen.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# festlegen der Zahlennotation}
\FunctionTok{options}\NormalTok{(}\AttributeTok{scipen =} \DecValTok{999}\NormalTok{)}
\CommentTok{\# Berechnen der Anteile der verschiedenen Länder an der weltweiten Weinproduktion in Prozent}
\NormalTok{df\_wine\_prod}\SpecialCharTok{$}\NormalTok{percent }\OtherTok{\textless{}{-}}\NormalTok{ df\_wine\_prod}\SpecialCharTok{$}\NormalTok{wineProducingCountries\_wineProduction}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(df\_wine\_prod}\SpecialCharTok{$}\NormalTok{wineProducingCountries\_wineProduction) }\SpecialCharTok{*} \DecValTok{100}
\CommentTok{\# Das selbe für die bewerteten Weine}
\NormalTok{df\_WW\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{percent }\OtherTok{\textless{}{-}}\NormalTok{df\_WW\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(df\_WW\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq) }\SpecialCharTok{*} \DecValTok{100}
\CommentTok{\# DF sortieren}
\NormalTok{df\_wine\_prod }\OtherTok{\textless{}{-}}\NormalTok{ df\_wine\_prod[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_wine\_prod}\SpecialCharTok{$}\NormalTok{percent),]}
\NormalTok{df\_WW\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_WW\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_WW\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{percent),]}

\CommentTok{\# Kuchendiagramm für die weltweiten Daten}
\NormalTok{pie\_WW\_prod }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(df\_wine\_prod[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,], }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =}\NormalTok{ percent, }\AttributeTok{fill =}\NormalTok{ country)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{width =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_polar}\NormalTok{(}\StringTok{"y"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_void}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Anteile an der weltweiten Weinproduktion je Land"}\NormalTok{)}

\CommentTok{\# Kuchendiagramm für die Weine aus dem Review{-}Datensatz}
\NormalTok{pie\_WW\_set }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(df\_WW\_wines\_by\_country[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,], }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{""}\NormalTok{, }\AttributeTok{y =}\NormalTok{ percent, }\AttributeTok{fill =}\NormalTok{ Var1)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{width =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"white"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_polar}\NormalTok{(}\StringTok{"y"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_void}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Anteile der Weine im Datensatz je Land"}\NormalTok{)}

\FunctionTok{grid.arrange}\NormalTok{(pie\_WW\_prod, pie\_WW\_set, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-8-1.pdf}

Hier können wir nun beobachten das das Verhältnis der bewerteten Weine
sich deutlich von dem der tatsächlichen weltweite Produktion
unterscheidet. Diese Disparität kann vielerlei Gründe haben, zum einen
ist das Magazin von welchem die Daten erhoben wurden Amerekanisch
weshalb ein gewisser Bias in die Richtung zu erwarten war. Die anderen
Unterschiede jedoch sind schwerer zu erklären wie zum Beispiel das
Australien der weltweit fünft größte Weinproduzent ist jedoch bei den
bewerteten Weinen nicht unter den Top 5 auftritt. Desweiteren werden
anscheinend überproportional mehr Portugisische Weine bewertet als
Portugal insgesammt anteilig produziert.

\subsubsection{Frage 5 - In welcher Relationen stehen die Länder in
Bezug auf die Anzahl der bewerteten Weine
zueinander?}\label{frage-5---in-welcher-relationen-stehen-die-luxe4nder-in-bezug-auf-die-anzahl-der-bewerteten-weine-zueinander}

Um herrauszufinden in welcher Relation die verschiedenen Länder
zueinander stehen, im Bezug auf den Anteil ihrer Weine im Datensatz
müssen wir die Daten zuerst nach Kontinent sortieren um sie dann weiter
zu verarbeiten. Dadurch das wir so viele verschiedene Länder und
verbindungen haben ist es sinvoller Subnetze für die verschiednen
Kontinente zu erstellen da so eine bessere übersicht herscht.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# zuerst legen wir listen mit allen Länder je kontinent an um anschließend die Daten zu vergleichen, hierbei ist darauf zu achten das die Namen der Länder im Datensatz exact die selben wie in den Listen ist}

\CommentTok{\# Länder in Asien}
\NormalTok{asia\_countries }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"Afghanistan"}\NormalTok{, }\StringTok{"Armenia"}\NormalTok{, }\StringTok{"Azerbaijan"}\NormalTok{, }\StringTok{"Bahrain"}\NormalTok{, }\StringTok{"Bangladesh"}\NormalTok{, }\StringTok{"Bhutan"}\NormalTok{, }
  \StringTok{"Brunei"}\NormalTok{, }\StringTok{"Cambodia"}\NormalTok{, }\StringTok{"China"}\NormalTok{, }\StringTok{"Cyprus"}\NormalTok{, }\StringTok{"Georgia"}\NormalTok{, }\StringTok{"India"}\NormalTok{, }\StringTok{"Indonesia"}\NormalTok{, }
  \StringTok{"Iran"}\NormalTok{, }\StringTok{"Iraq"}\NormalTok{, }\StringTok{"Israel"}\NormalTok{, }\StringTok{"Japan"}\NormalTok{, }\StringTok{"Jordan"}\NormalTok{, }\StringTok{"Kazakhstan"}\NormalTok{, }\StringTok{"Kuwait"}\NormalTok{, }
  \StringTok{"Kyrgyzstan"}\NormalTok{, }\StringTok{"Laos"}\NormalTok{, }\StringTok{"Lebanon"}\NormalTok{, }\StringTok{"Malaysia"}\NormalTok{, }\StringTok{"Maldives"}\NormalTok{, }\StringTok{"Mongolia"}\NormalTok{, }
  \StringTok{"Myanmar"}\NormalTok{, }\StringTok{"Nepal"}\NormalTok{, }\StringTok{"North Korea"}\NormalTok{, }\StringTok{"Oman"}\NormalTok{, }\StringTok{"Pakistan"}\NormalTok{, }\StringTok{"Palestine"}\NormalTok{, }
  \StringTok{"Philippines"}\NormalTok{, }\StringTok{"Qatar"}\NormalTok{, }\StringTok{"Saudi Arabia"}\NormalTok{, }\StringTok{"Singapore"}\NormalTok{, }\StringTok{"South Korea"}\NormalTok{, }
  \StringTok{"Sri Lanka"}\NormalTok{, }\StringTok{"Syria"}\NormalTok{, }\StringTok{"Taiwan"}\NormalTok{, }\StringTok{"Tajikistan"}\NormalTok{, }\StringTok{"Thailand"}\NormalTok{, }\StringTok{"Timor{-}Leste"}\NormalTok{, }
  \StringTok{"Turkey"}\NormalTok{, }\StringTok{"Turkmenistan"}\NormalTok{, }\StringTok{"United Arab Emirates"}\NormalTok{, }\StringTok{"Uzbekistan"}\NormalTok{, }
  \StringTok{"Vietnam"}\NormalTok{, }\StringTok{"Yemen"}
\NormalTok{)}

\CommentTok{\# Länder in Europa}
\NormalTok{europe\_countries }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"Albania"}\NormalTok{, }\StringTok{"Andorra"}\NormalTok{, }\StringTok{"Austria"}\NormalTok{, }\StringTok{"Belarus"}\NormalTok{, }\StringTok{"Belgium"}\NormalTok{, }
  \StringTok{"Bosnia and Herzegovina"}\NormalTok{, }\StringTok{"Bulgaria"}\NormalTok{, }\StringTok{"Croatia"}\NormalTok{, }\StringTok{"Cyprus"}\NormalTok{, }
  \StringTok{"Czech Republic"}\NormalTok{, }\StringTok{"Denmark"}\NormalTok{, }\StringTok{"Estonia"}\NormalTok{, }\StringTok{"Finland"}\NormalTok{, }\StringTok{"France"}\NormalTok{, }
  \StringTok{"Germany"}\NormalTok{, }\StringTok{"Greece"}\NormalTok{, }\StringTok{"Hungary"}\NormalTok{, }\StringTok{"Iceland"}\NormalTok{, }\StringTok{"Ireland"}\NormalTok{, }\StringTok{"Italy"}\NormalTok{, }
  \StringTok{"Kosovo"}\NormalTok{, }\StringTok{"Latvia"}\NormalTok{, }\StringTok{"Liechtenstein"}\NormalTok{, }\StringTok{"Lithuania"}\NormalTok{, }\StringTok{"Luxembourg"}\NormalTok{, }
  \StringTok{"Malta"}\NormalTok{, }\StringTok{"Moldova"}\NormalTok{, }\StringTok{"Monaco"}\NormalTok{, }\StringTok{"Montenegro"}\NormalTok{, }\StringTok{"Netherlands"}\NormalTok{, }
  \StringTok{"Macedonia"}\NormalTok{, }\StringTok{"Norway"}\NormalTok{, }\StringTok{"Poland"}\NormalTok{, }\StringTok{"Portugal"}\NormalTok{, }\StringTok{"Romania"}\NormalTok{, }
  \StringTok{"Russia"}\NormalTok{, }\StringTok{"San Marino"}\NormalTok{, }\StringTok{"Serbia"}\NormalTok{, }\StringTok{"Slovakia"}\NormalTok{, }\StringTok{"Slovenia"}\NormalTok{, }
  \StringTok{"Spain"}\NormalTok{, }\StringTok{"Sweden"}\NormalTok{, }\StringTok{"Switzerland"}\NormalTok{, }\StringTok{"Ukraine"}\NormalTok{, }\StringTok{"England"}\NormalTok{, }
  \StringTok{"Vatican City"}
\NormalTok{)}

\CommentTok{\# Länder in Afrika}
\NormalTok{africa\_countries }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"Algeria"}\NormalTok{, }\StringTok{"Angola"}\NormalTok{, }\StringTok{"Benin"}\NormalTok{, }\StringTok{"Botswana"}\NormalTok{, }\StringTok{"Burkina Faso"}\NormalTok{, }\StringTok{"Burundi"}\NormalTok{, }
  \StringTok{"Cabo Verde"}\NormalTok{, }\StringTok{"Cameroon"}\NormalTok{, }\StringTok{"Central African Republic"}\NormalTok{, }\StringTok{"Chad"}\NormalTok{, }
  \StringTok{"Comoros"}\NormalTok{, }\StringTok{"Democratic Republic of the Congo"}\NormalTok{, }\StringTok{"Djibouti"}\NormalTok{, }\StringTok{"Egypt"}\NormalTok{, }
  \StringTok{"Equatorial Guinea"}\NormalTok{, }\StringTok{"Eritrea"}\NormalTok{, }\StringTok{"Eswatini"}\NormalTok{, }\StringTok{"Ethiopia"}\NormalTok{, }\StringTok{"Gabon"}\NormalTok{, }
  \StringTok{"Gambia"}\NormalTok{, }\StringTok{"Ghana"}\NormalTok{, }\StringTok{"Guinea"}\NormalTok{, }\StringTok{"Guinea{-}Bissau"}\NormalTok{, }\StringTok{"Ivory Coast"}\NormalTok{, }
  \StringTok{"Kenya"}\NormalTok{, }\StringTok{"Lesotho"}\NormalTok{, }\StringTok{"Liberia"}\NormalTok{, }\StringTok{"Libya"}\NormalTok{, }\StringTok{"Madagascar"}\NormalTok{, }\StringTok{"Malawi"}\NormalTok{, }
  \StringTok{"Mali"}\NormalTok{, }\StringTok{"Mauritania"}\NormalTok{, }\StringTok{"Mauritius"}\NormalTok{, }\StringTok{"Morocco"}\NormalTok{, }\StringTok{"Mozambique"}\NormalTok{, }
  \StringTok{"Namibia"}\NormalTok{, }\StringTok{"Niger"}\NormalTok{, }\StringTok{"Nigeria"}\NormalTok{, }\StringTok{"Rwanda"}\NormalTok{, }\StringTok{"Sao Tome and Principe"}\NormalTok{, }
  \StringTok{"Senegal"}\NormalTok{, }\StringTok{"Seychelles"}\NormalTok{, }\StringTok{"Sierra Leone"}\NormalTok{, }\StringTok{"Somalia"}\NormalTok{, }\StringTok{"South Africa"}\NormalTok{, }
  \StringTok{"South Sudan"}\NormalTok{, }\StringTok{"Sudan"}\NormalTok{, }\StringTok{"Tanzania"}\NormalTok{, }\StringTok{"Togo"}\NormalTok{, }\StringTok{"Tunisia"}\NormalTok{, }\StringTok{"Uganda"}\NormalTok{, }
  \StringTok{"Zambia"}\NormalTok{, }\StringTok{"Zimbabwe"}
\NormalTok{)}

\CommentTok{\# Länder in Nord Amerika}
\NormalTok{north\_america\_countries }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"Canada"}\NormalTok{, }\StringTok{"US"}\NormalTok{, }\StringTok{"Mexico"}\NormalTok{, }\StringTok{"Guatemala"}\NormalTok{, }\StringTok{"Honduras"}\NormalTok{, }
  \StringTok{"El Salvador"}\NormalTok{, }\StringTok{"Nicaragua"}\NormalTok{, }\StringTok{"Costa Rica"}\NormalTok{, }\StringTok{"Panama"}\NormalTok{, }\StringTok{"Belize"}\NormalTok{, }
  \StringTok{"Cuba"}\NormalTok{, }\StringTok{"Jamaica"}\NormalTok{, }\StringTok{"Haiti"}\NormalTok{, }\StringTok{"Dominican Republic"}\NormalTok{, }\StringTok{"Puerto Rico"}\NormalTok{, }
  \StringTok{"Bahamas"}\NormalTok{, }\StringTok{"Trinidad and Tobago"}\NormalTok{, }\StringTok{"Barbados"}\NormalTok{, }\StringTok{"Saint Lucia"}\NormalTok{, }
  \StringTok{"Grenada"}\NormalTok{, }\StringTok{"Antigua and Barbuda"}\NormalTok{, }\StringTok{"Saint Vincent and the Grenadines"}\NormalTok{, }
  \StringTok{"Saint Kitts and Nevis"}
\NormalTok{)}

\CommentTok{\# Länder in Süd Amerika}
\NormalTok{south\_america\_countries }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"Argentina"}\NormalTok{, }\StringTok{"Brazil"}\NormalTok{, }\StringTok{"Chile"}\NormalTok{, }\StringTok{"Colombia"}\NormalTok{, }\StringTok{"Ecuador"}\NormalTok{, }\StringTok{"Peru"}\NormalTok{, }
  \StringTok{"Bolivia"}\NormalTok{, }\StringTok{"Paraguay"}\NormalTok{, }\StringTok{"Uruguay"}\NormalTok{, }\StringTok{"Venezuela"}\NormalTok{, }\StringTok{"Guyana"}\NormalTok{, }\StringTok{"Suriname"}\NormalTok{, }
  \StringTok{"French Guiana"}\NormalTok{, }\StringTok{"Falkland Islands"}
\NormalTok{)}

\CommentTok{\# Länder in Ozianien}
\NormalTok{oceania\_countries }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"Australia"}\NormalTok{, }\StringTok{"New Zealand"}\NormalTok{, }\StringTok{"Fiji"}\NormalTok{, }\StringTok{"Papua New Guinea"}\NormalTok{, }
  \StringTok{"Solomon Islands"}\NormalTok{, }\StringTok{"Vanuatu"}\NormalTok{, }\StringTok{"New Caledonia"}\NormalTok{, }\StringTok{"French Polynesia"}\NormalTok{, }
  \StringTok{"Samoa"}\NormalTok{, }\StringTok{"Tonga"}\NormalTok{, }\StringTok{"Kiribati"}\NormalTok{, }\StringTok{"Tuvalu"}\NormalTok{, }\StringTok{"Micronesia"}\NormalTok{, }
  \StringTok{"Marshall Islands"}\NormalTok{, }\StringTok{"Palau"}\NormalTok{, }\StringTok{"Nauru"}
\NormalTok{)}

\CommentTok{\# zuerst werden die spalte country in df mit den länderlisten abgegleicht, trift die Kondition zu so werden sie dem jeweiligen neun Kontinenten df zugewiesen}

\CommentTok{\# Süd Amerika}
\NormalTok{df\_SA }\OtherTok{\textless{}{-}}\NormalTok{ df[df}\SpecialCharTok{$}\NormalTok{country }\SpecialCharTok{\%in\%}\NormalTok{ south\_america\_countries,]}
\NormalTok{df\_SA\_wines\_by\_country }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{table}\NormalTok{(df\_SA}\SpecialCharTok{$}\NormalTok{country))}
\NormalTok{df\_SA\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_SA\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_SA\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq),]}

\CommentTok{\# Europa }
\NormalTok{df\_EU }\OtherTok{\textless{}{-}}\NormalTok{ df[df}\SpecialCharTok{$}\NormalTok{country }\SpecialCharTok{\%in\%}\NormalTok{ europe\_countries,]}
\NormalTok{df\_EU\_wines\_by\_country }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{table}\NormalTok{(df\_EU}\SpecialCharTok{$}\NormalTok{country))}
\NormalTok{df\_EU\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_EU\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_EU\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq),]}

\CommentTok{\# Nord Amerika}
\NormalTok{df\_NA }\OtherTok{\textless{}{-}}\NormalTok{ df[df}\SpecialCharTok{$}\NormalTok{country }\SpecialCharTok{\%in\%}\NormalTok{ north\_america\_countries,]}
\NormalTok{df\_NA\_wines\_by\_country }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{table}\NormalTok{(df\_NA}\SpecialCharTok{$}\NormalTok{country))}
\NormalTok{df\_NA\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_NA\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_NA\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq),]}

\CommentTok{\# Afrika}
\NormalTok{df\_AF }\OtherTok{\textless{}{-}}\NormalTok{ df[df}\SpecialCharTok{$}\NormalTok{country }\SpecialCharTok{\%in\%}\NormalTok{ africa\_countries,]}
\NormalTok{df\_AF\_wines\_by\_country }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{table}\NormalTok{(df\_AF}\SpecialCharTok{$}\NormalTok{country))}
\NormalTok{df\_AF\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_AF\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_AF\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq),]}

\CommentTok{\# Ozianien}
\NormalTok{df\_OZ }\OtherTok{\textless{}{-}}\NormalTok{ df[df}\SpecialCharTok{$}\NormalTok{country }\SpecialCharTok{\%in\%}\NormalTok{ oceania\_countries,]}
\NormalTok{df\_OZ\_wines\_by\_country }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{table}\NormalTok{(df\_OZ}\SpecialCharTok{$}\NormalTok{country))}
\NormalTok{df\_OZ\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_OZ\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_OZ\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq),]}

\CommentTok{\# Asien }
\NormalTok{df\_AS }\OtherTok{\textless{}{-}}\NormalTok{ df[df}\SpecialCharTok{$}\NormalTok{country }\SpecialCharTok{\%in\%}\NormalTok{ asia\_countries,]}
\NormalTok{df\_AS\_wines\_by\_country }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{table}\NormalTok{(df\_AS}\SpecialCharTok{$}\NormalTok{country))}
\NormalTok{df\_AS\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_AS\_wines\_by\_country[}\FunctionTok{order}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{df\_AS\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Freq),]}

\CommentTok{\# hier werden nun die Spalten jeweils umbenannt um besser mit ihnen weiterarbeiten zu können }
\NormalTok{df\_SA\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_SA\_wines\_by\_country }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{rename}\NormalTok{(}\AttributeTok{Country =}\NormalTok{ Var1, }\AttributeTok{Weight =}\NormalTok{ Freq)}
\NormalTok{df\_EU\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_EU\_wines\_by\_country }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{rename}\NormalTok{(}\AttributeTok{Country =}\NormalTok{ Var1, }\AttributeTok{Weight =}\NormalTok{ Freq)}
\NormalTok{df\_NA\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_NA\_wines\_by\_country }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{rename}\NormalTok{(}\AttributeTok{Country =}\NormalTok{ Var1, }\AttributeTok{Weight =}\NormalTok{ Freq)}
\NormalTok{df\_AF\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_AF\_wines\_by\_country }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{rename}\NormalTok{(}\AttributeTok{Country =}\NormalTok{ Var1, }\AttributeTok{Weight =}\NormalTok{ Freq)}
\NormalTok{df\_OZ\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_OZ\_wines\_by\_country }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{rename}\NormalTok{(}\AttributeTok{Country =}\NormalTok{ Var1, }\AttributeTok{Weight =}\NormalTok{ Freq)}
\NormalTok{df\_AS\_wines\_by\_country }\OtherTok{\textless{}{-}}\NormalTok{ df\_AS\_wines\_by\_country }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{rename}\NormalTok{(}\AttributeTok{Country =}\NormalTok{ Var1, }\AttributeTok{Weight =}\NormalTok{ Freq)}
\end{Highlighting}
\end{Shaded}

Der nächste Schritt ist nun die Graphen für die jeweiligen Kontinente zu
erstellen. Das verfahren wird nun exemplarisch an Süd Amerika
veranschaulicht, die anderen Graphen werden auf die exakt selbe Weise
erstellt.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# adjancy matrix erstellen}
\NormalTok{adj\_SA }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{( }\AttributeTok{country\_1=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{country\_2=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{adj=}\FunctionTok{numeric}\NormalTok{()}
\NormalTok{)}
\CommentTok{\# zähler für die folgende While schleife aufsetzen}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_SA\_wines\_by\_country)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_SA\_wines\_by\_country)}

\CommentTok{\#zuweisen der Länder zueinander damit jede beziehung zwischen jedem Land berechnet werden kann }
\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}=} \DecValTok{1}\NormalTok{) \{  }

\NormalTok{  country\_1 }\OtherTok{\textless{}{-}}\NormalTok{ df\_SA\_wines\_by\_country[i, }\DecValTok{1}\NormalTok{]}
\NormalTok{  country\_2 }\OtherTok{\textless{}{-}}\NormalTok{ df\_SA\_wines\_by\_country[z, }\DecValTok{1}\NormalTok{]}

  \CommentTok{\# adjacency berechnen, wie ähnlch die Anzahl der weine ist}
\NormalTok{  adj }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(df\_SA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_SA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_SA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_SA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_SA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_SA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{]) }\SpecialCharTok{\textgreater{}} \DecValTok{10}\NormalTok{,}
    \ConstantTok{NA}\NormalTok{,}
    \FunctionTok{ifelse}\NormalTok{(df\_SA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_SA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_SA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_SA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_SA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_SA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{])}
\NormalTok{  )}

  \CommentTok{\# Reihe formatieren und in die Matrix einfügen}
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{country\_1 =}\NormalTok{ country\_1, }\AttributeTok{country\_2 =}\NormalTok{ country\_2, }\AttributeTok{adj =}\NormalTok{ adj)}
\NormalTok{  adj\_SA }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(adj\_SA, row\_data)}

  \CommentTok{\# Counter setzen}
\NormalTok{  z }\OtherTok{\textless{}{-}}\NormalTok{ z }\SpecialCharTok{{-}} \DecValTok{1}

  \ControlFlowTok{if}\NormalTok{ (z }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
\NormalTok{    i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{    z }\OtherTok{\textless{}{-}}\NormalTok{ i}
\NormalTok{  \}}
\NormalTok{\}}
\CommentTok{\# NA Werte entfernen und den leeren Graphen erstellen}
\NormalTok{adj\_SA }\OtherTok{\textless{}{-}}\FunctionTok{na.omit}\NormalTok{(adj\_SA)}
\NormalTok{graph\_SA }\OtherTok{\textless{}{-}} \FunctionTok{graph.empty}\NormalTok{()}

\CommentTok{\# größe der Nodes berechnen (nach totaler Anzahl der Weine)}
\NormalTok{vertex\_size\_SA }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country =} \FunctionTok{character}\NormalTok{(),}\AttributeTok{Size =} \FunctionTok{numeric}\NormalTok{())}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_SA\_wines\_by\_country)}
\ControlFlowTok{while}\NormalTok{(i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)\{}
\NormalTok{  Country }\OtherTok{=}\NormalTok{ df\_SA\_wines\_by\_country[i,}\DecValTok{1}\NormalTok{]}
\NormalTok{  Size }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(df\_SA\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{100} \SpecialCharTok{\textgreater{}} \DecValTok{2}\NormalTok{, (df\_SA\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000}\NormalTok{)}\SpecialCharTok{+}\DecValTok{7}\NormalTok{, }\DecValTok{7}\NormalTok{)}
  \FunctionTok{add\_row}\NormalTok{(vertex\_size\_SA, }\AttributeTok{Country=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{Size=}\FunctionTok{numeric}\NormalTok{())}
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country=}\NormalTok{Country,}\AttributeTok{Size=}\NormalTok{Size)}
\NormalTok{  vertex\_size\_SA }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(vertex\_size\_SA,row\_data)}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{  vertex\_size\_SA }\OtherTok{\textless{}{-}}\NormalTok{ vertex\_size\_SA[}\FunctionTok{order}\NormalTok{(vertex\_size\_SA}\SpecialCharTok{$}\NormalTok{Size, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{),]}
\NormalTok{\}}

\CommentTok{\# Nodes hinzufügen}
\NormalTok{graph\_SA }\OtherTok{\textless{}{-}} \FunctionTok{add\_vertices}\NormalTok{(graph\_SA, }\AttributeTok{n =} \FunctionTok{nrow}\NormalTok{(df\_SA\_wines\_by\_country), }\AttributeTok{name =}\NormalTok{ df\_SA\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Country, }\AttributeTok{size =}\NormalTok{ vertex\_size\_SA}\SpecialCharTok{$}\NormalTok{Size)}

\CommentTok{\# Edges hinzufügen}
\NormalTok{i}\OtherTok{\textless{}{-}}\FunctionTok{nrow}\NormalTok{(adj\_SA)}
\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  graph\_SA }\OtherTok{\textless{}{-}} \FunctionTok{add\_edges}\NormalTok{(graph\_SA, }\AttributeTok{edges =} \FunctionTok{as.matrix}\NormalTok{(adj\_SA[i, }\FunctionTok{c}\NormalTok{(}\StringTok{"country\_1"}\NormalTok{, }\StringTok{"country\_2"}\NormalTok{)]))}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
  
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{adj\_EU }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{( }\AttributeTok{country\_1=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{country\_2=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{adj=}\FunctionTok{numeric}\NormalTok{()}
\NormalTok{)}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_EU\_wines\_by\_country)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_EU\_wines\_by\_country)}


\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}=} \DecValTok{1}\NormalTok{) \{  }

\NormalTok{  country\_1 }\OtherTok{\textless{}{-}}\NormalTok{ df\_EU\_wines\_by\_country[i, }\DecValTok{1}\NormalTok{]}
\NormalTok{  country\_2 }\OtherTok{\textless{}{-}}\NormalTok{ df\_EU\_wines\_by\_country[z, }\DecValTok{1}\NormalTok{]}

\NormalTok{  adj }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(df\_EU\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_EU\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_EU\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_EU\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_EU\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_EU\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{]) }\SpecialCharTok{\textgreater{}} \DecValTok{10}\NormalTok{,}
    \ConstantTok{NA}\NormalTok{,}
    \FunctionTok{ifelse}\NormalTok{(df\_EU\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_EU\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_EU\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_EU\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_EU\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_EU\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{])}
\NormalTok{  )}

  
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{country\_1 =}\NormalTok{ country\_1, }\AttributeTok{country\_2 =}\NormalTok{ country\_2, }\AttributeTok{adj =}\NormalTok{ adj)}
\NormalTok{  adj\_EU }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(adj\_EU, row\_data)}

\NormalTok{  z }\OtherTok{\textless{}{-}}\NormalTok{ z }\SpecialCharTok{{-}} \DecValTok{1}

  \ControlFlowTok{if}\NormalTok{ (z }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
\NormalTok{    i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{    z }\OtherTok{\textless{}{-}}\NormalTok{ i}
\NormalTok{  \}}
\NormalTok{\}}
\NormalTok{adj\_EU }\OtherTok{\textless{}{-}}\FunctionTok{na.omit}\NormalTok{(adj\_EU)}
\NormalTok{graph\_EU }\OtherTok{\textless{}{-}} \FunctionTok{graph.empty}\NormalTok{()}

\NormalTok{vertex\_size\_EU }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country =} \FunctionTok{character}\NormalTok{(),}\AttributeTok{Size =} \FunctionTok{numeric}\NormalTok{())}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_EU\_wines\_by\_country)}
\ControlFlowTok{while}\NormalTok{(i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)\{}
\NormalTok{  Country }\OtherTok{=}\NormalTok{ df\_EU\_wines\_by\_country[i,}\DecValTok{1}\NormalTok{]}
\NormalTok{  Size }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(df\_EU\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000} \SpecialCharTok{\textgreater{}} \DecValTok{2}\NormalTok{, (df\_EU\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000}\NormalTok{)}\SpecialCharTok{+}\DecValTok{7}\NormalTok{, }\DecValTok{7}\NormalTok{)}
  \FunctionTok{add\_row}\NormalTok{(vertex\_size\_EU, }\AttributeTok{Country=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{Size=}\FunctionTok{numeric}\NormalTok{())}
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country=}\NormalTok{Country,}\AttributeTok{Size=}\NormalTok{Size)}
\NormalTok{  vertex\_size\_EU }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(vertex\_size\_EU,row\_data)}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{  vertex\_size\_EU }\OtherTok{\textless{}{-}}\NormalTok{ vertex\_size\_EU[}\FunctionTok{order}\NormalTok{(vertex\_size\_EU}\SpecialCharTok{$}\NormalTok{Size, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{),]}
\NormalTok{\}}

\NormalTok{graph\_EU }\OtherTok{\textless{}{-}} \FunctionTok{add\_vertices}\NormalTok{(graph\_EU, }\AttributeTok{n =} \FunctionTok{nrow}\NormalTok{(df\_EU\_wines\_by\_country), }\AttributeTok{name =}\NormalTok{ df\_EU\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Country, }\AttributeTok{size =}\NormalTok{ vertex\_size\_EU}\SpecialCharTok{$}\NormalTok{Size)}

\NormalTok{i}\OtherTok{\textless{}{-}}\FunctionTok{nrow}\NormalTok{(adj\_EU)}
\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  graph\_EU }\OtherTok{\textless{}{-}} \FunctionTok{add\_edges}\NormalTok{(graph\_EU, }\AttributeTok{edges =} \FunctionTok{as.matrix}\NormalTok{(adj\_EU[i, }\FunctionTok{c}\NormalTok{(}\StringTok{"country\_1"}\NormalTok{, }\StringTok{"country\_2"}\NormalTok{)]))}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
  
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{adj\_NA }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{( }\AttributeTok{country\_1=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{country\_2=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{adj=}\FunctionTok{numeric}\NormalTok{()}
\NormalTok{)}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_NA\_wines\_by\_country)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_NA\_wines\_by\_country)}


\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}=} \DecValTok{1}\NormalTok{) \{  }

\NormalTok{  country\_1 }\OtherTok{\textless{}{-}}\NormalTok{ df\_NA\_wines\_by\_country[i, }\DecValTok{1}\NormalTok{]}
\NormalTok{  country\_2 }\OtherTok{\textless{}{-}}\NormalTok{ df\_NA\_wines\_by\_country[z, }\DecValTok{1}\NormalTok{]}

\NormalTok{  adj }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(df\_NA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_NA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_NA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_NA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_NA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_NA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{]) }\SpecialCharTok{\textgreater{}} \DecValTok{10}\NormalTok{,}
    \ConstantTok{NA}\NormalTok{,}
    \FunctionTok{ifelse}\NormalTok{(df\_NA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_NA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_NA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_NA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_NA\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_NA\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{])}
\NormalTok{  )}


\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{country\_1 =}\NormalTok{ country\_1, }\AttributeTok{country\_2 =}\NormalTok{ country\_2, }\AttributeTok{adj =}\NormalTok{ adj)}
\NormalTok{  adj\_NA }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(adj\_NA, row\_data)}

\NormalTok{  z }\OtherTok{\textless{}{-}}\NormalTok{ z }\SpecialCharTok{{-}} \DecValTok{1}

  \ControlFlowTok{if}\NormalTok{ (z }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
\NormalTok{    i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{    z }\OtherTok{\textless{}{-}}\NormalTok{ i}
\NormalTok{  \}}
\NormalTok{\}}
\NormalTok{adj\_NA }\OtherTok{\textless{}{-}}\FunctionTok{na.omit}\NormalTok{(adj\_NA)}
\NormalTok{graph\_NA }\OtherTok{\textless{}{-}} \FunctionTok{graph.empty}\NormalTok{()}

\NormalTok{vertex\_size\_NA }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country =} \FunctionTok{character}\NormalTok{(),}\AttributeTok{Size =} \FunctionTok{numeric}\NormalTok{())}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_NA\_wines\_by\_country)}
\ControlFlowTok{while}\NormalTok{(i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)\{}
\NormalTok{  Country }\OtherTok{=}\NormalTok{ df\_NA\_wines\_by\_country[i,}\DecValTok{1}\NormalTok{]}
\NormalTok{  Size }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(df\_NA\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000} \SpecialCharTok{\textgreater{}} \DecValTok{2}\NormalTok{, (df\_NA\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000}\NormalTok{)}\SpecialCharTok{+}\DecValTok{7}\NormalTok{, }\DecValTok{7}\NormalTok{)}
  \FunctionTok{add\_row}\NormalTok{(vertex\_size\_NA, }\AttributeTok{Country=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{Size=}\FunctionTok{numeric}\NormalTok{())}
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country=}\NormalTok{Country,}\AttributeTok{Size=}\NormalTok{Size)}
\NormalTok{  vertex\_size\_NA }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(vertex\_size\_NA,row\_data)}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{  vertex\_size\_NA }\OtherTok{\textless{}{-}}\NormalTok{ vertex\_size\_NA[}\FunctionTok{order}\NormalTok{(vertex\_size\_NA}\SpecialCharTok{$}\NormalTok{Size, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{),]}
\NormalTok{\}}

\NormalTok{graph\_NA }\OtherTok{\textless{}{-}} \FunctionTok{add\_vertices}\NormalTok{(graph\_NA, }\AttributeTok{n =} \FunctionTok{nrow}\NormalTok{(df\_NA\_wines\_by\_country), }\AttributeTok{name =}\NormalTok{ df\_NA\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Country, }\AttributeTok{size =}\NormalTok{ vertex\_size\_NA}\SpecialCharTok{$}\NormalTok{Size)}

\NormalTok{i}\OtherTok{\textless{}{-}}\FunctionTok{nrow}\NormalTok{(adj\_NA)}
\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  graph\_NA }\OtherTok{\textless{}{-}} \FunctionTok{add\_edges}\NormalTok{(graph\_NA, }\AttributeTok{edges =} \FunctionTok{as.matrix}\NormalTok{(adj\_NA[i, }\FunctionTok{c}\NormalTok{(}\StringTok{"country\_1"}\NormalTok{, }\StringTok{"country\_2"}\NormalTok{)]))}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
  
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{adj\_AS }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{( }\AttributeTok{country\_1=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{country\_2=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{adj=}\FunctionTok{numeric}\NormalTok{()}
\NormalTok{)}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_AS\_wines\_by\_country)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_AS\_wines\_by\_country)}


\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}=} \DecValTok{1}\NormalTok{) \{  }

\NormalTok{  country\_1 }\OtherTok{\textless{}{-}}\NormalTok{ df\_AS\_wines\_by\_country[i, }\DecValTok{1}\NormalTok{]}
\NormalTok{  country\_2 }\OtherTok{\textless{}{-}}\NormalTok{ df\_AS\_wines\_by\_country[z, }\DecValTok{1}\NormalTok{]}

\NormalTok{  adj }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(df\_AS\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_AS\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_AS\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_AS\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_AS\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_AS\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{]) }\SpecialCharTok{\textgreater{}} \DecValTok{10}\NormalTok{,}
    \ConstantTok{NA}\NormalTok{,}
    \FunctionTok{ifelse}\NormalTok{(df\_AS\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_AS\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_AS\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_AS\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_AS\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_AS\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{])}
\NormalTok{  )}

  
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{country\_1 =}\NormalTok{ country\_1, }\AttributeTok{country\_2 =}\NormalTok{ country\_2, }\AttributeTok{adj =}\NormalTok{ adj)}
\NormalTok{  adj\_AS }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(adj\_AS, row\_data)}

\NormalTok{  z }\OtherTok{\textless{}{-}}\NormalTok{ z }\SpecialCharTok{{-}} \DecValTok{1}

  \ControlFlowTok{if}\NormalTok{ (z }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
\NormalTok{    i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{    z }\OtherTok{\textless{}{-}}\NormalTok{ i}
\NormalTok{  \}}
\NormalTok{\}}
\NormalTok{adj\_AS }\OtherTok{\textless{}{-}}\FunctionTok{na.omit}\NormalTok{(adj\_AS)}
\NormalTok{graph\_AS }\OtherTok{\textless{}{-}} \FunctionTok{graph.empty}\NormalTok{()}

\NormalTok{vertex\_size\_AS }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country =} \FunctionTok{character}\NormalTok{(),}\AttributeTok{Size =} \FunctionTok{numeric}\NormalTok{())}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_AS\_wines\_by\_country)}
\ControlFlowTok{while}\NormalTok{(i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)\{}
\NormalTok{  Country }\OtherTok{=}\NormalTok{ df\_AS\_wines\_by\_country[i,}\DecValTok{1}\NormalTok{]}
\NormalTok{  Size }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(df\_AS\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{100} \SpecialCharTok{\textgreater{}} \DecValTok{5}\NormalTok{, (df\_AS\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{100}\NormalTok{)}\SpecialCharTok{+}\DecValTok{7}\NormalTok{, }\DecValTok{7}\NormalTok{)}
  \FunctionTok{add\_row}\NormalTok{(vertex\_size\_AS, }\AttributeTok{Country=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{Size=}\FunctionTok{numeric}\NormalTok{())}
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country=}\NormalTok{Country,}\AttributeTok{Size=}\NormalTok{Size)}
\NormalTok{  vertex\_size\_AS }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(vertex\_size\_AS,row\_data)}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{  vertex\_size\_AS }\OtherTok{\textless{}{-}}\NormalTok{ vertex\_size\_AS[}\FunctionTok{order}\NormalTok{(vertex\_size\_AS}\SpecialCharTok{$}\NormalTok{Size, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{),]}
\NormalTok{\}}

\NormalTok{graph\_AS }\OtherTok{\textless{}{-}} \FunctionTok{add\_vertices}\NormalTok{(graph\_AS, }\AttributeTok{n =} \FunctionTok{nrow}\NormalTok{(df\_AS\_wines\_by\_country), }\AttributeTok{name =}\NormalTok{ df\_AS\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Country, }\AttributeTok{size =}\NormalTok{ vertex\_size\_AS}\SpecialCharTok{$}\NormalTok{Size)}

\NormalTok{i}\OtherTok{\textless{}{-}}\FunctionTok{nrow}\NormalTok{(adj\_AS)}
\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  graph\_AS }\OtherTok{\textless{}{-}} \FunctionTok{add\_edges}\NormalTok{(graph\_AS, }\AttributeTok{edges =} \FunctionTok{as.matrix}\NormalTok{(adj\_AS[i, }\FunctionTok{c}\NormalTok{(}\StringTok{"country\_1"}\NormalTok{, }\StringTok{"country\_2"}\NormalTok{)]))}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{adj\_AF }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{( }\AttributeTok{country\_1=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{country\_2=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{adj=}\FunctionTok{numeric}\NormalTok{()}
\NormalTok{)}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_AF\_wines\_by\_country)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_AF\_wines\_by\_country)}

\NormalTok{adj\_AF }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{()  }

\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}=} \DecValTok{1}\NormalTok{) \{  }

\NormalTok{  country\_1 }\OtherTok{\textless{}{-}}\NormalTok{ df\_AF\_wines\_by\_country[i, }\DecValTok{1}\NormalTok{]}
\NormalTok{  country\_2 }\OtherTok{\textless{}{-}}\NormalTok{ df\_AF\_wines\_by\_country[z, }\DecValTok{1}\NormalTok{]}

\NormalTok{  adj }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(df\_AF\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_AF\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_AF\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_AF\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_AF\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_AF\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{]) }\SpecialCharTok{\textgreater{}} \DecValTok{10}\NormalTok{,}
    \ConstantTok{NA}\NormalTok{,}
    \FunctionTok{ifelse}\NormalTok{(df\_AF\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_AF\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_AF\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_AF\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_AF\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_AF\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{])}
\NormalTok{  )}

  
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{country\_1 =}\NormalTok{ country\_1, }\AttributeTok{country\_2 =}\NormalTok{ country\_2, }\AttributeTok{adj =}\NormalTok{ adj)}
\NormalTok{  adj\_AF }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(adj\_AF, row\_data)}

\NormalTok{  z }\OtherTok{\textless{}{-}}\NormalTok{ z }\SpecialCharTok{{-}} \DecValTok{1}

  \ControlFlowTok{if}\NormalTok{ (z }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
\NormalTok{    i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{    z }\OtherTok{\textless{}{-}}\NormalTok{ i}
\NormalTok{  \}}
\NormalTok{\}}
\NormalTok{adj\_AF }\OtherTok{\textless{}{-}}\FunctionTok{na.omit}\NormalTok{(adj\_AF)}
\NormalTok{graph\_AF }\OtherTok{\textless{}{-}} \FunctionTok{graph.empty}\NormalTok{()}

\NormalTok{vertex\_size\_AF }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country =} \FunctionTok{character}\NormalTok{(),}\AttributeTok{Size =} \FunctionTok{numeric}\NormalTok{())}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_AF\_wines\_by\_country)}
\ControlFlowTok{while}\NormalTok{(i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)\{}
\NormalTok{  Country }\OtherTok{=}\NormalTok{ df\_AF\_wines\_by\_country[i,}\DecValTok{1}\NormalTok{]}
\NormalTok{  Size }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(df\_AF\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000} \SpecialCharTok{\textgreater{}} \DecValTok{2}\NormalTok{, (df\_AF\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000}\NormalTok{)}\SpecialCharTok{+}\DecValTok{7}\NormalTok{, }\DecValTok{7}\NormalTok{)}
  \FunctionTok{add\_row}\NormalTok{(vertex\_size\_AF, }\AttributeTok{Country=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{Size=}\FunctionTok{numeric}\NormalTok{())}
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country=}\NormalTok{Country,}\AttributeTok{Size=}\NormalTok{Size)}
\NormalTok{  vertex\_size\_AF }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(vertex\_size\_AF,row\_data)}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{  vertex\_size\_AF }\OtherTok{\textless{}{-}}\NormalTok{ vertex\_size\_AF[}\FunctionTok{order}\NormalTok{(vertex\_size\_AF}\SpecialCharTok{$}\NormalTok{Size, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{),]}
\NormalTok{\}}

\NormalTok{graph\_AF }\OtherTok{\textless{}{-}} \FunctionTok{add\_vertices}\NormalTok{(graph\_AF, }\AttributeTok{n =} \FunctionTok{nrow}\NormalTok{(df\_AF\_wines\_by\_country), }\AttributeTok{name =}\NormalTok{ df\_AF\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Country, }\AttributeTok{size =}\NormalTok{ vertex\_size\_AF}\SpecialCharTok{$}\NormalTok{Size)}

\NormalTok{i}\OtherTok{\textless{}{-}}\FunctionTok{nrow}\NormalTok{(adj\_AF)}
\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  graph\_AF }\OtherTok{\textless{}{-}} \FunctionTok{add\_edges}\NormalTok{(graph\_AF, }\AttributeTok{edges =} \FunctionTok{as.matrix}\NormalTok{(adj\_AF[i, }\FunctionTok{c}\NormalTok{(}\StringTok{"country\_1"}\NormalTok{, }\StringTok{"country\_2"}\NormalTok{)]))}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
  
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{adj\_OZ }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{( }\AttributeTok{country\_1=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{country\_2=}\FunctionTok{character}\NormalTok{(),}\AttributeTok{adj=}\FunctionTok{numeric}\NormalTok{()}
\NormalTok{)}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_OZ\_wines\_by\_country)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_OZ\_wines\_by\_country)}

\NormalTok{adj\_OZ }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{()  }

\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}=} \DecValTok{1}\NormalTok{) \{  }

\NormalTok{  country\_1 }\OtherTok{\textless{}{-}}\NormalTok{ df\_OZ\_wines\_by\_country[i, }\DecValTok{1}\NormalTok{]}
\NormalTok{  country\_2 }\OtherTok{\textless{}{-}}\NormalTok{ df\_OZ\_wines\_by\_country[z, }\DecValTok{1}\NormalTok{]}

\NormalTok{  adj }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
    \FunctionTok{ifelse}\NormalTok{(df\_OZ\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_OZ\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_OZ\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_OZ\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_OZ\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_OZ\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{]) }\SpecialCharTok{\textgreater{}} \DecValTok{10}\NormalTok{,}
    \ConstantTok{NA}\NormalTok{,}
    \FunctionTok{ifelse}\NormalTok{(df\_OZ\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{\textgreater{}}\NormalTok{ df\_OZ\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_OZ\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_OZ\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{],}
\NormalTok{           df\_OZ\_wines\_by\_country[i, }\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ df\_OZ\_wines\_by\_country[z, }\DecValTok{2}\NormalTok{])}
\NormalTok{  )}

  
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{country\_1 =}\NormalTok{ country\_1, }\AttributeTok{country\_2 =}\NormalTok{ country\_2, }\AttributeTok{adj =}\NormalTok{ adj)}
\NormalTok{  adj\_OZ }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(adj\_OZ, row\_data)}

\NormalTok{  z }\OtherTok{\textless{}{-}}\NormalTok{ z }\SpecialCharTok{{-}} \DecValTok{1}

  \ControlFlowTok{if}\NormalTok{ (z }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
\NormalTok{    i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{    z }\OtherTok{\textless{}{-}}\NormalTok{ i}
\NormalTok{  \}}
\NormalTok{\}}
\NormalTok{adj\_OZ }\OtherTok{\textless{}{-}}\FunctionTok{na.omit}\NormalTok{(adj\_OZ)}
\NormalTok{graph\_OZ }\OtherTok{\textless{}{-}} \FunctionTok{graph.empty}\NormalTok{()}

\NormalTok{vertex\_size\_OZ }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country =} \FunctionTok{character}\NormalTok{(),}\AttributeTok{Size =} \FunctionTok{numeric}\NormalTok{())}
\NormalTok{i }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df\_OZ\_wines\_by\_country)}
\ControlFlowTok{while}\NormalTok{(i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)\{}
\NormalTok{  Country }\OtherTok{=}\NormalTok{ df\_OZ\_wines\_by\_country[i,}\DecValTok{1}\NormalTok{]}
\NormalTok{  Size }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(df\_OZ\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000} \SpecialCharTok{\textgreater{}} \DecValTok{2}\NormalTok{, (df\_OZ\_wines\_by\_country[i,}\DecValTok{2}\NormalTok{]}\SpecialCharTok{/}\DecValTok{1000}\NormalTok{)}\SpecialCharTok{+}\DecValTok{7}\NormalTok{, }\DecValTok{7}\NormalTok{)}
  \FunctionTok{add\_row}\NormalTok{(vertex\_size\_OZ, }\AttributeTok{Country=}\FunctionTok{character}\NormalTok{(), }\AttributeTok{Size=}\FunctionTok{numeric}\NormalTok{())}
\NormalTok{  row\_data }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}\AttributeTok{Country=}\NormalTok{Country,}\AttributeTok{Size=}\NormalTok{Size)}
\NormalTok{  vertex\_size\_OZ }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(vertex\_size\_OZ,row\_data)}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
\NormalTok{  vertex\_size\_OZ }\OtherTok{\textless{}{-}}\NormalTok{ vertex\_size\_OZ[}\FunctionTok{order}\NormalTok{(vertex\_size\_OZ}\SpecialCharTok{$}\NormalTok{Size, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{),]}
\NormalTok{\}}

\NormalTok{graph\_OZ }\OtherTok{\textless{}{-}} \FunctionTok{add\_vertices}\NormalTok{(graph\_OZ, }\AttributeTok{n =} \FunctionTok{nrow}\NormalTok{(df\_OZ\_wines\_by\_country), }\AttributeTok{name =}\NormalTok{ df\_OZ\_wines\_by\_country}\SpecialCharTok{$}\NormalTok{Country, }\AttributeTok{size =}\NormalTok{ vertex\_size\_OZ}\SpecialCharTok{$}\NormalTok{Size)}

\NormalTok{i}\OtherTok{\textless{}{-}}\FunctionTok{nrow}\NormalTok{(adj\_OZ)}
\ControlFlowTok{while}\NormalTok{ (i }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{  graph\_OZ }\OtherTok{\textless{}{-}} \FunctionTok{add\_edges}\NormalTok{(graph\_OZ, }\AttributeTok{edges =} \FunctionTok{as.matrix}\NormalTok{(adj\_OZ[i, }\FunctionTok{c}\NormalTok{(}\StringTok{"country\_1"}\NormalTok{, }\StringTok{"country\_2"}\NormalTok{)]))}
\NormalTok{  i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{{-}} \DecValTok{1}
  
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Bei den folgenden Netwerken ist auf folgendes zu achten:

\begin{itemize}
\item
  Die Nodes sind die Herkunftsländer der Weine
\item
  Eine Verbindung zwischen 2 nodes bedeutet das sie eine gewisse
  Ähnlichkeit in der Anzahl der Weine im Datensatz aufweisen
\item
  die Länge dieser Verbindung stellt den Grad der Ähnlichkeit da, so
  kürzer die Verbindung zweier nodes ist desto ähnlicher ist die Anzahl
  der Weine im Datensatz
\item
  Die Richtung der Verbindung gibt an welches der Beiden Länder mehr
  Weine besitzt
\item
  die Größe der Nodes skaliert mit ihrer Gesamtanzahl an Weinen
\item
  Eine verbindung zwischen zwei Ländern wird nur dann angezeigt wenn das
  eine Land maximal 10 mal so viel Weine wie das andere zum Datensatz
  beisteuert
\end{itemize}

\paragraph{Europa}\label{europa}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{layout }\OtherTok{=} \FunctionTok{layout\_with\_graphopt}\NormalTok{(graph\_EU)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{simplify}\NormalTok{(graph\_EU), }\AttributeTok{edge.arrow.size =} \FloatTok{0.2}\NormalTok{,}\AttributeTok{layout =}\NormalTok{ layout, }\AttributeTok{main =} \StringTok{"Europa"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-16-1.pdf}

In Europa ist zu beobachten das Besonders die beiden Hauptproduzenten
Italien und Frankreich eine enge Bindung haben, weiterhin kann man sehen
das Griechenland als Bindeglied der beiden aufzufindenden Cluster
agiert. Der eine Cluster, hier oben zu sehen, besteht aus vor allem
Osteuropäischen Ländern sowie den Balkanstaaten. Der andere Cluster,
hier unten zu sehen, besteht vor allem aus Süd und Westeuropäischen
Ländern. Als größter Produzent ist hier Frankreich zu identifizieren.

\paragraph{Asien}\label{asien}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{layout }\OtherTok{=} \FunctionTok{layout\_with\_graphopt}\NormalTok{(graph\_AS)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{simplify}\NormalTok{(graph\_AS), }\AttributeTok{edge.arrow.size =} \FloatTok{0.2}\NormalTok{,}\AttributeTok{layout =}\NormalTok{ layout, }\AttributeTok{main =} \StringTok{"Asien"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-17-1.pdf}

In Asien gibt es keine wirklche Clusterbildung, man kann zwar erkennen
das Israel der Hauptproduzent dieser Region ist, jedoch nicht mit
astronomischem Abstand, die Türkei ist in diesem Netzwerk außerdem
wichtig da sie viele Beziehungen mit anderen Nodes hat.

\paragraph{Africa}\label{africa}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{layout }\OtherTok{=} \FunctionTok{layout\_with\_graphopt}\NormalTok{(graph\_AF)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{simplify}\NormalTok{(graph\_AF), }\AttributeTok{edge.arrow.size =} \FloatTok{0.2}\NormalTok{,}\AttributeTok{layout =}\NormalTok{ layout, }\AttributeTok{main =} \StringTok{"Afrika"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-18-1.pdf}

In Afrika ensteht die Situation das keines der 3 Länder eine Beziehung
hat, daraus kann man schließen das es keine Konstelationen von Ländern
gibt wo das eine Land maximal 10 mal so viele weine Beiträgt wie das
andere. Somit haben wir hier ein Netzwerk ohne Beziehungen.

\paragraph{Süd Amerika}\label{suxfcd-amerika}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{layout }\OtherTok{=} \FunctionTok{layout\_with\_graphopt}\NormalTok{(graph\_SA)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{simplify}\NormalTok{(graph\_SA), }\AttributeTok{edge.arrow.size =} \FloatTok{0.2}\NormalTok{,}\AttributeTok{layout =}\NormalTok{ layout, }\AttributeTok{main =} \StringTok{"Süd Amerika"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-19-1.pdf}

In Südamerika kommt es zu einer interessanten Clusterbildung, die beiden
Länder Chile und Argentinien haben eine Verbindung, die beiden Länder
sind auch auf dem Weltmarkt durchaus wichtige Produzenten. Ein weiterer
Cluster bilden die Länder: Peru, Uruguay und Brazilien, kleinere
Lateinamerikanische Länder welche nicht besonders relevant sind auf dem
Weltmarkt, jedoch lässt sich aus dem Netzwerk ablesen das sie ein
Dreieck bilden, dass bedeutet das sie ungefähr alle gleich viele Weine
zum Datensatz beitragen.

\paragraph{Nord Amerika}\label{nord-amerika}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{layout }\OtherTok{=} \FunctionTok{layout\_with\_graphopt}\NormalTok{(graph\_NA)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{simplify}\NormalTok{(graph\_NA), }\AttributeTok{edge.arrow.size =} \FloatTok{0.2}\NormalTok{,}\AttributeTok{layout =}\NormalTok{ layout, }\AttributeTok{main =} \StringTok{"Nord Amerika"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-20-1.pdf}

In Nord Amerika zeichnet sich ein zu erwartendes Bild ab, die USA
stellen mit großem Abstand die meisten Weine, eine weitere Beziehung
besteht zwar zwischen Mexico und Kanada, diese ist jedoch nicht von
besonderer Bedeutung.

\paragraph{Ozianien}\label{ozianien}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{layout }\OtherTok{=} \FunctionTok{layout\_with\_graphopt}\NormalTok{(graph\_OZ)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{simplify}\NormalTok{(graph\_OZ), }\AttributeTok{edge.arrow.size =} \FloatTok{0.2}\NormalTok{,}\AttributeTok{layout =}\NormalTok{ layout, }\AttributeTok{main =} \StringTok{"Ozianien"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Report_files/figure-latex/unnamed-chunk-21-1.pdf}

Abschließend sehen wir in Ozianien, nur die Bindung zwischen Australien
und Neuseeland. Diese beiden Länder sind die einzigen die im Datensatz
vom Kontinent Ozianien vertreten sind. Überaschenderweise ist Australien
verhältnismäßig klein da es nicht besonder viele Weine dem Datensatz
stellt. Auf dem Weltmarkt jedoch ist Australien eine wichtige
Exportnation.

\subsection{Conclusio}\label{conclusio}

Abschließend lassen sich folgende Erfgebnisse festhalten:

\begin{itemize}
\item
  Die USA sind das Land welches die meisten weine im Datensatz stellen:
  54504 (41.9\%)
\item
  England hat mit 91,581 Punkten den höchsten Punktedurchschnitt im
  Datensatz wobei die USA mit 0.0133 den geringsten Standartfehler
  aufweisen
\item
  Das beste Punkte zu Preis Verhältnis hat die Ukraine mit 9,124, am
  schlechtesten schneidet die Schweiz mit 1,039 ab
\item
  Nach analyse der vertretenden Nationen sowie der Weltweiten Produktion
  von Wein lässt sich feststellen das der Datensatz einen starken
  USA-Bias hat und vor allem Weine aus den USA enthält
\item
  Australische Weine unterproprtional viel Bewertet und Portugisische
  überproportional viel.
\item
  In Europa sind zwei Cluster zu erkennen im Bezug auf die ähnlichkeit
  der Anzahl der Weine

  \begin{itemize}
  \item
    Cluster 1 besteht vor allem aus kleineren West \& mitteleuropäischen
    Staaten sowei dem Balkan und Osteuropa
  \item
    Cluster 2 besteht aus den Großen Süd, West und Mitteleuropäischen
    Ländern
  \item
    Griechenland liegt als Bindeglied zwischen den beiden
  \end{itemize}
\item
  In Asien sind keine Cluster zu erkennen nur Israel und die Türkei
  spielen eine wichtige Rolle da sie verhältnismäßig viel Produzieren
\item
  In Afrika existiert keine Verbindung zwischen den Ländern da sie alle
  zu sehr unterschiedliche mengen an Wein zum Datensatz beitragen
\item
  in Süd Amerika existieren 2 Cluster:

  \begin{itemize}
  \item
    Cluster 1 bestehend aus Argentienen und Chile, zwei auch weltweit
    bedeutende Weinexportnationen
  \item
    Cluster 2 besteht aus Uruguay, Brazilien und Peru welche jeweils
    ähnlich viel beitragen aber aus weltweiter Perspektive eher
    unerheblich sind
  \end{itemize}
\item
  In Nordamerika ist nur die Dominanz der USA im Datensatz abzusehen
  sowie eine nicht besonders wichtige verbindung zwischen mexico und
  Kanada
\item
  In Ozianien kann man nur die Verbindung zwischen Australien und
  Neuseeland sehen da diese Länder die einzigen beiden aus der Region
  sind die im Datensatz vertreten sind

  \begin{itemize}
  \tightlist
  \item
    Australien sollte aufgrund seiner wichtigen Rolle auf dem Weltmarkt
    eigentlich eine größere Menge an weinen Stellen
  \end{itemize}
\end{itemize}

\end{document}
